face-recognition:
  streams:
    cameras:
      - name: "backyard"
        url: "rtsp://localhost:8554/backyard?video&audio"
      # - name: "front-door"
      #   url: "rtsp://another-camera/stream"
  training:
    dataset-path: "trained_dataset.xml"
    root-folder: "training"
  mqtt:
    enabled: true
    broker: "tcp://localhost:1883"
    client-id: "face-recognition-service"
    username: ""
    password: ""
    topic-prefix: "double-take"
    qos: 0
    connection-timeout: 10
    keep-alive-interval: 60
